name: Create Config File

on:
  push:
    branches:
      - main  # or master, depending on your default branch

jobs:
  create-config:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create config directory if it doesn't exist
        run: mkdir -p src/config

      - name: Create config.js
        run: |
          echo 'export const CONFIG = { ANTHROPIC_API_KEY: "${{ secrets.ANTHROPIC_API_KEY }}" };' > src/config/config.js

      - name: List directory contents to verify
        run: |
          ls -la src/config/
          cat src/config/config.js
